sonar.projectKey=AnaGli_pos-fiap-os-service
sonar.projectName=pos-fiap-os-service
sonar.sources=app
sonar.tests=tests
sonar.test.inclusions=tests/**/*.py
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
sonar.organization=anagli
sonar.coverage.exclusions=app/alembic/**
