apiVersion: apps/v1
kind: Deployment
metadata:
  name: os-service-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: os-service-consumer
  template:
    metadata:
      labels:
        app: os-service-consumer
    spec:
      containers:
        - name: consumer
          image: anaglislere/os-service-tech-challenge:latest
          command: ["python", "-m", "app.messaging.consumer"]
          envFrom:
            - secretRef:
                name: os-service-secrets
            - configMapRef:
                name: os-service-config
