apiVersion: v1
kind: Secret
metadata:
  name: os-service-secrets
type: Opaque
stringData:
  DATABASE_URL: postgresql+psycopg://user:password@host:5432/os_service
  RABBITMQ_URL: amqp://workshop:password@rabbitmq.workshop.svc.cluster.local:5672/workshop
